<?php
declare(strict_types=1);
/**
 * @Create by PhpStorm
 * @author:jinxiu89@163.com
 * @Create Date:2020/5/28 9:23
 * @User: admin
 * @Current File : baseAdmin.php
 * @格言：溪涧岂能留得住，终归大海做波涛 --李忱
 * @格言： 我的内心因看见大海而波涛汹涌
 **/

namespace app\admin\controller;

use app\BaseController;
use think\App;
use think\facade\Session;
use think\facade\View;
use app\admin\middleware\Auth;

/**
 * Class baseAdmin
 * @package app\admin\controller
 */
class BaseAdmin extends BaseController
{
    protected $service;
    protected $validate;
    protected $language;

    protected $middleware = [Auth::class];

    /**
     * baseAdmin constructor.
     * @param App $app
     */
    public function __construct(App $app)
    {
        parent::__construct($app);
    }

    /**
     *
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->language = Session::get('current_language');
        /*if(Session::get('adminLogin', false) == false){
            View::assign('not_login',true);
        }*/
    }

    public function changeStatus()
    {

    }

    public function index()
    {
        try {
            return View::fetch();
        } catch (\Exception $e) {
        }
    }

    public function welcome()
    {
        try {
            return View::fetch();
        } catch (\Exception $e) {
        }
    }
}