<?php

namespace app\frontend\controller\home;

use app\frontend\controller\Base;
use think\App;
use think\facade\Env;
use think\facade\Session;
use think\facade\View;
use app\frontend\service\Prettiest;

/**
 * Class Index
 * @package app\frontend\controller\home
 * 首页相关的页面渲染
 */
class Index extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * Index constructor.
     * @param App $app
     */
    public function __construct(App $app)
    {
        parent::__construct($app);
        View::assign('language', Session::get('language'));
    }

    /**
     * @return string protected $type = [
     * '1' => '幻灯片(活动/新品)',
     * '2' => '热门(实力担当)',
     * '3' => '重金打造(镇馆之宝)',
     * '4' => '霸屏横幅(实力推荐)'];
     */
    public function index()
    {
        if ($this->request->isGet()) {
            $Prettiest = new Prettiest();
            $banner = $Prettiest->getPrettiest((int)1, (int)$this->language['id'], (int)1); //type 见函数注释
            $hot = array_slice($Prettiest->getPrettiest((int)2, (int)$this->language['id'], (int) 1), 0, 3); //第二个三个图的数据
            $starProduct = array_slice($Prettiest->getPrettiest((int)3, (int)$this->language['id'], (int) 1), 0, 4);
            View::assign('banner', $banner);
            View::assign('hot', $hot);
            View::assign('starProduct', $starProduct);
            return View::fetch($this->template . '/home/index.html');
        }
    }
}