<?php

namespace app\frontend\controller\home;

use app\frontend\controller\Base;
use think\App;
use think\facade\Env;
use think\facade\Session;
use think\facade\View;

/**
 * Class Index
 * @package app\frontend\controller\home
 * 首页相关的页面渲染
 */
class Index extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * Index constructor.
     * @param App $app
     */
    public function __construct(App $app)
    {
        parent::__construct($app);
        View::assign('language', Session::get('language'));
    }

    public function index()
    {
        if ($this->request->isGet()) {
            return View::fetch($this->template.'/home/index.html');
        }
    }
}
