<?php
/**
 * @Create by PhpStorm
 * @author:jinxiu89@163.com
 * @Create Date:2020/7/4 14:39
 * @User: admin
 * @Current File : base.php
 * @格言：溪涧岂能留得住，终归大海做波涛 --李忱
 * @格言： 我的内心因看见大海而波涛汹涌
 **/

namespace app\frontend\controller;


use app\BaseController;
use think\App;
use app\frontend\middleware\Location;

/**
 * Class Base
 * @package app\frontend\controller
 */
class Base extends BaseController
{
    protected $service;
    protected $middleware = [Location::class];

    /**
     * 在tp中，initialize 在__construct前面运行
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * Base constructor.
     * @param App $app
     */
    public function __construct(App $app)
    {
        parent::__construct($app);
    }

}