<?php
/**
 * @Create by PhpStorm
 * @author:jinxiu89@163.com
 * @Create Date:2020/7/4 14:47
 * @User: admin
 * @Current File : Index.php
 * @格言：溪涧岂能留得住，终归大海做波涛 --李忱
 * @格言： 我的内心因看见大海而波涛汹涌
 **/

namespace app\frontend\controller\supports;


use app\frontend\controller\Base;
use think\App;

class Index extends Base
{
    public function __construct(App $app)
    {
        parent::__construct($app);
    }
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}